###
# This is the place to override the opsworks_nodejs cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_nodejs/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# Upload corresponding deb file in my-opsworks-bucket-o-stuff bucket inside /packages/ubuntu/14.04/opsworks-nodejs_<your_nodejs_version>-1_amd64.deb
# default[:opsworks_nodejs][:version] = '12.16.3'
