source 'https://supermarket.chef.io'

cookbook 'alb_support', path: './alb_support'
cookbook 'ruby', path: './ruby'
cookbook 'deploy', path: './deploy'
cookbook 'deploy_user', path: './deploy_user'
cookbook 'nginx', path: './nginx'
cookbook 'node', path: './node'
cookbook 'papertrail', path: './papertrail'
cookbook 'puma', path: './puma'
cookbook 'sidekiq', path: './sidekiq'
cookbook 'whenever', path: './whenever'
